services:
  mlflow:
    build: .
    container_name: mlflow
    restart: always
  environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRESS_HOST: db
      POSTGRESS_DB: ${DB_NAME}
      POSTGRESS_PORT: ${DB_PORT}
      POSTGRES_DB: mlflow
  volumes:
    - artifact_storage:/home/mlflow/mlruns
  networks:
    - mlflow

  db:
    container_name: tracking_db
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - mlflow
  
  volumes:
    db_volume:
    artifact_storage:

  networks:
    mlflow: